### ISSUE TITLE
Apoc function calls from 4.2.0.5 error on neo4j causal cluster 4.2.7-enterprise

### ISSUE THREAD

**Issue by gwvandesteeg** [neo4j-contrib/neo4j-apoc-procedures#2044]
## Expected Behavior (Mandatory)

Running any apoc call works on a leader node in a causal cluster

## Actual Behavior (Mandatory)

Any apoc call results in the following error, no matter what node you are on.
Server at neo4j-core-1.neo4j.default.svc.cluster.local:7687 no longer accepts writes

## How to Reproduce the Problem

Create a configMap to pass additional configuration options via environment vars to the causal cluster
Create a causal cluster of 3 core nodes, and 0 readReplicas using the neo4j-helm chart v4.2.7-2 on kubernetes 1.20 (we're using EKS), the core and readReplica nodes are provided the configMap (core.configMap, and readReplica.configMap, in the values.yaml)

configmap contains the following environment variables:
```
NEO4J_apoc_export_file_enabled="true"
NEO4J_apoc_import_file_enabled="true"
NEO4J_apoc_trigger_enabled="true"
NEO4J_apoc_ttl_enabled="true"
NEO4J_apoc_uuid_enabled="true"
```
values.yaml contains the below
```yaml
core:
  standalone: false
  numberOfServers: 3
  configMap: neo4j-additional-envvars
  additionalVolumeMounts:
    - name: neo4j-logs
      mountPath: /data/logs
  additionalVolumes:
    - name: neo4j-logs
      emptyDir: {}
readReplica:
  numberOfServers: 0
  configMap: neo4j-additional-envvars
  additionalVolumeMounts:
    - name: neo4j-logs
      mountPath: /data/logs
  additionalVolumes:
    - name: neo4j-logs
      emptyDir: {}
```

### Simple Dataset (where it's possibile)

This is used to configure the users and additional database on the causal cluster.
```
:use system

CREATE DATABASE project IF NOT EXISTS;

CREATE USER master IF NOT EXISTS SET PASSWORD "<secret>" SET PASSWORD CHANGE NOT REQUIRED SET STATUS ACTIVE;
GRANT ROLE architect TO master;
CREATE USER graphql IF NOT EXISTS SET PASSWORD "<secret>" SET PASSWORD CHANGE NOT REQUIRED SET STATUS ACTIVE;
GRANT ROLE reader TO graphql;
```
Then when the database is actually getting used (this is a test scenario on the `neo4j` database), and this is the part that causes the problems.
```
CREATE (g:Greeting {message: "hello, world"}) RETURN g;
CREATE CONSTRAINT ON (g:Greeting) ASSERT g.uuid IS UNIQUE;
CALL apoc.uuid.install("Greeting");
MATCH (n) RETURN n;
```
The issue also occurs using `apoc.trigger.add`, which indicates it is not constrained to just one apoc function call.

### Steps (Mandatory)

  1. Create Neo4j cluster as per above details
  1. Setup causal cluster as per above cypher queries (connected via cypher-shell inside the cluster itself using `neo4j://neo4j.default.svc.cluster.local`)
  1. Connect to the causal cluster using the cypher-shell as the default `neo4j` admin user and the `neo4j://neo4j.default.svc.cluster.local` connection address and run the second set of commands (which is the apoc call). Whichever node you connect to is irrelevant, it happens on all of the 3 nodes in the causal cluster.
  1. The error occurs on the `CALL apoc.uuid.install("Greeting"): however the subsequent `MATCH` statement shows that the apoc call completed.  All the nodes now have a `uuid` property and value.

If we instead instantiate the cluster using the 4.0.7-enterprise image (make sure you delete the storage volumes/pvcs prior), everything works fine.

## Screenshots (where it's possibile)

```
neo4j@neo4j> MATCH (n) RETURN n LIMIT 1;
+---------------------------------------+
| n                                     |
+---------------------------------------+
| (:Greeting {message: "hello, world"}) |
+---------------------------------------+

11 rows available after 2 ms, consumed after another 0 ms

neo4j@neo4j> CREATE CONSTRAINT ON (g:Greeting) ASSERT g.uuid IS UNIQUE;
0 rows available after 58 ms, consumed after another 0 ms
Added 1 constraints

neo4j@neo4j> CALL apoc.uuid.install("Greeting");
Server at neo4j-core-1.neo4j.default.svc.cluster.local:7687 no longer accepts writes
```

## Specifications (Mandatory)

Currently used versions

### Versions

  - Kubernetes: 1.20 (eks)
  - OS: worker nodes running Amazon Linux
  - Neo4j: 4.2.7-enterprise
  - Neo4j-Apoc: 4.2.0.5
