### ISSUE TITLE
Improve docs about configuration with env variables

### ISSUE THREAD

**Issue by akshaymhetre** [neo4j-contrib/neo4j-apoc-procedures#2120]
I am using neo4j with docker version 4.2.5 and cypher file to initialize data.

I am setting following environment property to initialize data with docker-compose -

NEO4J_apoc_initializer_cypher=CALL apoc.cypher.runFile ("file:///sample.cypher")

This works fine and load the data after server started. However, you cannot create indexes in this file. You need runSchema call to create indexes. As per doc for neo4j 4.2, you can run multiple cypher,

NEO4J_apoc_initializer_cypher_0=CALL apoc.cypher.runSchemaFile ("file:///schema.cypher")

NEO4J_apoc_initializer_cypher_1=CALL apoc.cypher.runFile ("file:///sample.cypher")

However, this throws error:

unknown settings: apoc.initializer.cypher.0

unknown settings: apoc.initializer.cypher.1

Raised [this](https://github.com/neo4j/docker-neo4j/issues/290) on neo4j docker site as well.

**Comment by conker84** [comment]
@akshaymhetre can you please try with?:
```
apoc_initializer_cypher_0=CALL apoc.cypher.runSchemaFile ("file:///schema.cypher")
apoc_initializer_cypher_1=CALL apoc.cypher.runFile ("file:///sample.cypher")
```
Looking forward to hearing from you!

**Comment by aowss** [comment]
Sorry @conker84 , i am confused. I might not have understood your comment correctly.
Are you suggesting to just drop the leading `NEO4J_` part?

That's strange because :

- all the docs ( including some of your comments on other issues ) mention that prefix
- all the other environment variables seem to start with that prefix
- the error message `unknown settings: apoc.initializer.cypher.0` seems to have stripped that prefix

**Comment by conker84** [comment]
> Sorry @conker84 , i am confused. I might not have understood your comment correctly.
> Are you suggesting to just drop the leading `NEO4J_` part?
> 
> That's strange because :
> 
> * all the docs ( including some of your comments on other issues ) mention that prefix
> * all the other environment variables seem to start with that prefix
> * the error message `unknown settings: apoc.initializer.cypher.0` seems to have stripped that prefix

Yes @aowss you understood correctly, we leverage under-the-hood Apache Configuration that should be capable of recognising that kind of env variable and configure APOC properly.
I did a mistake in the copy and paste in the previous comment, use this env variable:

```
apoc.initializer.cypher.0=CALL apoc.cypher.runSchemaFile ("file:///schema.cypher")
apoc.initializer.cypher.1=CALL apoc.cypher.runFile ("file:///sample.cypher")
```

As I said Apache Configuration should be capable of understanding these.
Please lemme know

**Comment by aowss** [comment]
Thanks for your help,
Your solution seems to be working ( i am going to look more closely ).
But it makes the configuration inconsistent in terms of naming ( and the docs need to be updated )

```
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_dbms_logs_debug_level: DEBUG
      NEO4J_apoc_import_file_enabled: "true"
      apoc.initializer.cypher.0: "CALL apoc.cypher.runSchemaFile('constraints.cypher')"
      apoc.initializer.cypher.1: "CALL apoc.cypher.runFiles(['nodes.cypher', 'relationships.cypher'])"
      NEO4JLABS_PLUGINS: '["apoc"]'
```
