### ISSUE TITLE
Error: No jar URL found for version '4.4.9' in versions.json from 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json'

### ISSUE THREAD

**Issue by Scorpion2115** [neo4j-contrib/neo4j-apoc-procedures#3081]
I want to deploy `neo4j:4.4.9-enterprise` via docker-compose and install apoc + gds plugins.
This is my docker-compose.yml
```yml
---
version: '3'
services:

  neo4j:
    image: neo4j:4.4.9-enterprise
    hostname: neo4j
    container_name: neo4j
    ports:
    - "7474:7474"
    - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_AUTH=neo4j/admin
      # install plugins
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      # grant permissions to the APOC function and procedures
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
```

Unfortunately, I've got this error message
`Error: No jar URL found for version '4.4.9' in versions.json from 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json`

But I can clearly see the uri from the link of versions.json
```json
[
    {
        "neo4j": "4.4.9",
        "neo4jVersion": "4.4.9",
        "apoc": "4.4.0.7",
        "version": "4.4.0.7",
        "url": "http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.4.0.7",
        "homepageUrl": "http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.4.0.7",
        "jar": "https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.4.0.7/apoc-4.4.0.7-all.jar",
        "downloadUrl": "https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.4.0.7/apoc-4.4.0.7-all.jar",
        "sha1": "657525b5c854026325ecf739d0a91ac4d4003921",
        "sha256": "58fcf00c4e50075714cc88a3d345dd718c79400f5beff93c1bbc7387e4a079eb",
        "md5": "49a52964f5b22d9e94df114e141626b4",
        "config": {
            "+:dbms.security.procedures.unrestricted": [
                "apoc.*"
            ]
        }
    },
...
```
