### ISSUE TITLE
Extended is missing apoc.load.json, apoc.version, maybe more?

### ISSUE THREAD

**Issue by cramatt** [neo4j-contrib/neo4j-apoc-procedures#3359]
## Expected Behavior (Mandatory)

Based on the docs I have read, APOC core is a subset of APOC extended. Meaning that extended should have ALL functions of core plus some. Assuming this is correct, when using extended 5.2.0 I see that at least 2 functions are missing which are in core 5.2.1, they are as follows:

```
apoc.version
apoc.load.json
```

I would expect that in extended AND core these would both work.

## Actual Behavior (Mandatory)

The two functions noted above are not available when using extended 5.2.0.

### Steps (Mandatory)

1. Create a docker-compose file like so:

```
version: '3.3'
services:
  neo4j:
    image: neo4j:5.2.0
    ports:
      - "7474:7474" # neo4j browser
      - "7687:7687" # neo4j bolt
    volumes:
        - ./plugins:/plugins
        - ./data:/data
        - ./conf:/conf
        - ./logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password1234!
      -
```

2. Create a directory called `/plugins` and add the extended APOC extended plugin from here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/5.2.0

3. Create a directory called `/config` and add the following file: 

```
# apoc.conf
apoc.import.file.enabled=true
apoc.ttl.enabled=false
apoc.uuid.enabled=false
```

4. Create directory `/logs` and `/data`

5. Start docker `docker-compose up`
6. Wait for logs indicating docker is running
7. Visit browser http://localhost:7474/browser/
8. Run `RETURN apoc.version() as OUTPUT`
9. Run `CALL apoc.load.json()`
10. See errors

## Screenshots (where it's possibile)

![image](https://user-images.githubusercontent.com/22599518/206329135-6b36a156-75be-49e0-8e96-8ec05b5aa89a.png)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Windows / Docker CE 4.3.1
  - Neo4j: 5.2 community edition
  - Neo4j-Apoc: 5.2 extended
