### ISSUE TITLE
Neo4j 5.26.5 + APOC 5.26.0: Registered Cypher-based Custom Procedures Not Found in neo4j DB

### ISSUE THREAD

**Issue by lei-lqc** [neo4j-contrib/neo4j-apoc-procedures#4407]
Neo4j Version: 5.26.5 (Neo4j Desktop)
APOC Plugin: apoc-5.26.0-extended.jar
Environment: macOS / Neo4j Desktop

Issue Summary
I successfully registered a Cypher-based custom procedure under the system database using:

:use system
CALL apoc.custom.installProcedure(
  'custom.hello(input :: MAP) :: (value :: MAP)',
  '
  RETURN {message: "Hello, " + input.name} AS value
  ',
  'neo4j',
  'READ'
)

After registering, I confirmed the procedure was listed with CALL apoc.custom.list under :use neo4j.

However, when I try to call the procedure inside the neo4j database, I consistently receive:
`Neo.ClientError.Procedure.ProcedureNotFound`

I actually followed that document edited my procedures :
https://neo4j.com/labs/apoc/5/cypher-execution/cypher-based-procedures-functions/

###Things I’ve Confirmed

* The procedure is listed under `CALL apoc.custom.list` in `neo4j` database
* The procedure was registered from the `system` database as required
* Restarting the DB does not help

**Comment by vga91** [comment]
Hi! I think I found what’s going on here.

You're correctly installing a custom procedure using `apoc.custom.installProcedure`, but there are a few small gotchas that might be causing the issue:
__________
### 1. Procedure name prefix
When you define a procedure like this:
```cypher
CALL apoc.custom.installProcedure(
  'custom.hello(input :: MAP) :: (value :: MAP)',
  'RETURN {message: "Hello, " + $input.name} AS value',
  'neo4j',
  'READ'
)
```
It will automatically be registered under the `custom.` namespace.
So if the name you provide is `custom.hello`, the full name to call it becomes:
```cypher
CALL custom.custom.hello({name: "Neo"})
```
That double `custom` might look odd, but it’s expected behavior.
To avoid that, you can just name it `'hello(...)'`, and then call it like:
__________
### 2. Cypher parameter syntax
In the Cypher query, input parameters must be referenced with the `$` prefix.
So instead of:
```cypher
'RETURN {message: "Hello, " + input.name} AS value'
```
You should write:
```cypher
'RETURN {message: "Hello, " + $input.name} AS value'
```
__________
### 3. Refresh delay for custom procedures
After installing a custom procedure or function, it may not be immediately available.
APOC uses a refresh interval (by default 60 seconds) before the new procedure becomes callable.
You can control this interval using the config:
```cypher
apoc.custom.procedures.refresh=<MILLISECONDS>
```
For testing purposes, you can reduce it to something like `1000` (1 s) in your neo4j.conf or container environment.
__________
### Bonus: test environment (Docker Compose)
Here’s the docker-compose.yml I used to quickly test the issue and confirm the fix, in case it helps others:
```yml
version: '3.5'
services:
  neo4guy:
    image: neo4j:5.26.5-enterprise-bullseye
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/neo4guypass
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_logs_debug_level: DEBUG
      NEO4J_dbms_security_procedures_unrestricted: apoc.*,algo.*,gds.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*,algo.*,gds.*
      NEO4J_dbms_security_allow__csv__import__from__file__urls: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_trigger_enabled: true
      NEO4J_apoc_custom_procedures_refresh: 1000 # lowered refresh to 1s for testing
      NEO4JLABS_PLUGINS: "[\"apoc\",\"apoc-extended\"]"
    networks:
      - neo4test
networks:
  neo4test:
    driver: bridge
```
